In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet(r"/home/Nema/UniCRS_GraphRAG/Recommendation_GraphRAG/output/train_step0/artifacts/create_final_entities.parquet")
# mask = df['title'] == 'ARGO (2012)'
# df[mask]
df

,id,human_readable_id,title,type,description,text_unit_ids
0,95c85ba8-6bce-43b7-ad26-fa1419cc62eb,0,BEN-HUR (1959),MOVIE,"An epic film released in 1959, known for its g...",[4de866f2212ce103cd0a20857f269e552334429b8bd6c...
1,ca9ebfa4-01c1-43ad-aaad-c4e88d17786c,1,LAWRENCE OF ARABIA (1962),MOVIE,A 1962 epic historical drama film,[4de866f2212ce103cd0a20857f269e552334429b8bd6c...
2,43e5e4ee-8c78-4013-8f3e-f75387316234,2,GLADIATOR (2000),MOVIE,GLADIATOR (2000) is a 2000 epic historical dra...,[4de866f2212ce103cd0a20857f269e552334429b8bd6c...
3,8f993753-e1a7-4edf-9833-33c3fdf302e1,3,GONE WITH THE WIND (1939),MOVIE,A classic 1939 romance film,[4de866f2212ce103cd0a20857f269e552334429b8bd6c...
4,fd279c31-b346-4722-8c2a-41bd36c747bf,4,WONDER WOMAN (2017),MOVIE,A 2017 superhero film featuring the character ...,[4de866f2212ce103cd0a20857f269e552334429b8bd6c...
...,...,...,...,...,...,...
184,f27a632e-9df7-4a05-be9c-f6ac2427dbab,184,SLASHER,,,[d2dba9652b30fb9f81dad00b0f1a044d202ea6f3b4e0b...
185,c5a6e1b2-b2e8-44b9-99a0-aeaa9d7e891f,185,GORE,,,[d2dba9652b30fb9f81dad00b0f1a044d202ea6f3b4e0b...
186,399bdc20-143c-45f7-a7aa-27981da3eaab,186,SCIENCE FICTION,,,[d2dba9652b30fb9f81dad00b0f1a044d202ea6f3b4e0b...
187,59bbcaaa-5c2b-4ce2-8805-b3bed664c576,187,MICHAEL MYERS,HALLOWEEN (1978),Michael Myers is a horror character\nMichael M...,[d2dba9652b30fb9f81dad00b0f1a044d202ea6f3b4e0b...
188,95cc3300-f744-4436-b764-991538bf46ec,188,CHARACTER,,,[d2dba9652b30fb9f81dad00b0f1a044d202ea6f3b4e0b...

In [12]:
import pandas as pd

df = pd.read_parquet(r"/home/Nema/UniCRS_GraphRAG/Recommendation_GraphRAG/output/train_step0/artifacts/create_final_relationships.parquet")
mask = (df['source'] == 'ARGO (2012)') | (df['target'] == 'ARGO (2012)')
df_filtered = df[mask]

df_filtered

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids
0,ff8d31c5-42b0-4090-a424-48a334e4c0d3,0,ARGO (2012),BEN AFFLECK,Ben Affleck starred in Argo),1.0,3,[4de866f2212ce103cd0a20857f269e552334429b8bd6c...

In [12]:
entities_df = pd.read_parquet(r"/home/Nema/UniCRS_GraphRAG/Recommendation_GraphRAG/output/test_dialogue/artifacts/create_final_entities.parquet")
# Step 1: Filter first 5 "MOVIE" type entities
movies_filtered = entities_df[entities_df["type"] == "MOVIE"].head(8)

# Step 2: Keep all rows with types other than "MOVIE"
other_types = entities_df[entities_df["type"] != "MOVIE"]

# Step 3: Concatenate the results
filtered_df = pd.concat([movies_filtered, other_types])

pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)     # Show all rows
pd.set_option('display.max_colwidth', None) # Prevent text truncation
filtered_df[['human_readable_id', 'title', 'type', 'description']]
# entities_df

,human_readable_id,title,type,description
0,0,SUPER TROOPERS (2001),MOVIE,A 2001 comedy film known for its humor and quirky characters
1,1,POLICE ACADEMY (1984),MOVIE,A 1984 comedy film that is known for its humor and ensemble cast
2,2,AMERICAN PIE (1999),MOVIE,A 1999 comedy film that became a cultural phenomenon
3,3,LETHAL WEAPON (1987),MOVIE,A 1987 action film known for its buddy cop dynamic
4,4,BEVERLY HILLS COP (1984),MOVIE,A 1984 action comedy film starring Eddie Murphy
5,5,48 HRS. (1982),MOVIE,A 1982 action comedy film starring Nick Nolte and Eddie Murphy
6,6,A NIGHTMARE ON ELM STREET (1984),MOVIE,"A 1984 horror film known for its iconic villain, Freddy Krueger"
7,7,HAPPY DEATH DAY (2017),MOVIE,A 2017 horror film with a unique time loop premise
28,28,EDDIE MURPHY,ACTOR,American actor known for his roles in comedy films like Beverly Hills Cop (1984) and The Nutty Professor (1996)
29,29,JASON BATEMAN,ACTOR,American actor known for his roles in comedies like Identity Thief (2013) and Horrible Bosses (2011)
30,30,MELISSA MCCARTHY,ACTOR,American actress known for her comedic roles in films like Identity Thief (2013) and The Heat (2013)
31,31,EMMA STONE,ACTOR,American actress known for her roles in films like Easy A (2010) and La La Land (2016)
32,32,QUENTIN TARANTINO,DIRECTOR,Renowned filmmaker known for his unique storytelling and direction in films like Pulp Fiction (1994) and Kill Bill (2003)
33,33,JOHN TRAVOLTA,ACTOR,American actor known for his roles in films like Pulp Fiction (1994) and Grease (1978)
34,34,SAMUEL L. JACKSON,ACTOR,American actor known for his roles in films like Pulp Fiction (1994) and The Avengers (2012)
35,35,UMA THURMAN,ACTOR,American actress known for her roles in films like Pulp Fiction (1994) and Kill Bill (2003)
36,36,PULP FICTION (1994),,
38,38,X-MEN,GENRE,"A genre featuring mutants and superpowers, as seen in X-Men: The Last Stand (2006)"
47,47,SUPERHERO,,
48,48,HORROR,,
49,49,COMEDY-DRAMA,,
50,50,COMEDY,,

In [15]:
relationship_df = pd.read_parquet(r"/home/Nema/UniCRS_GraphRAG/Recommendation_GraphRAG/output/test_dialogue/artifacts/create_final_relationships.parquet")
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)     # Show all rows
pd.set_option('display.max_colwidth', None) # Prevent text truncation
relationship_df[['human_readable_id', 'source',	'target', 'description']]

,human_readable_id,source,target,description
0,0,SUPER TROOPERS (2001),POLICE ACADEMY (1984),Both Super Troopers (2001) and Police Academy (1984) are comedy films known for their humor and ensemble casts.
1,1,POLICE ACADEMY (1984),AMERICAN PIE (1999),Both American Pie (1999) and Police Academy (1984) are comedy films known for their humor and cultural impact.
2,2,LETHAL WEAPON (1987),BEVERLY HILLS COP (1984),Lethal Weapon (1987) and Beverly Hills Cop (1984) are action comedy films from the 1980s.
3,3,BEVERLY HILLS COP (1984),EDDIE MURPHY,"Eddie Murphy stars in Beverly Hills Cop, a classic action comedy film from 1984."
4,4,A NIGHTMARE ON ELM STREET (1984),HAPPY DEATH DAY (2017),Both A Nightmare on Elm Street (1984) and Happy Death Day (2017) are horror films with unique premises.
5,5,THE LAST HOUSE ON THE LEFT (1972),THE FOREST (2016),The Last House on the Left (1972) and The Forest (2016) are horror films known for their intense and suspenseful storytelling.
6,6,IDENTITY THIEF (2013),THE HEAT (2013),Identity Thief (2013) and The Heat (2013) are comedy films starring Melissa McCarthy.
7,7,IDENTITY THIEF (2013),JASON BATEMAN,"Jason Bateman stars in Identity Thief, a comedy film from 2013."
8,8,IDENTITY THIEF (2013),MELISSA MCCARTHY,"Melissa McCarthy stars in Identity Thief, showcasing her comedic talent."
9,9,THE HEAT (2013),MELISSA MCCARTHY,"Melissa McCarthy stars in The Heat, a comedy film from 2013."
10,10,EASY A (2010),AVENGERS: INFINITY WAR (2018),Easy A (2010) and Avengers: Infinity War (2018) are movies from different genres.
11,11,EASY A (2010),EMMA STONE,"Emma Stone stars in Easy A, a comedy film from 2010."
12,12,THE BLACK PANTHERS: VANGUARD OF THE REVOLUTION (2015),CLICK (2006),The Black Panthers: Vanguard of the Revolution (2015) and Click (2006) are movies from different genres.
13,13,IT (2017),THE WATERBOY (1998),It (2017) and The Waterboy (1998) are movies from different genres.
14,14,ANT-MAN (2015),IRON MAN 2 (2010),Ant-Man (2015) and Iron Man 2 (2010) are superhero movies from different franchises.
15,15,THE AVENGERS (2012),SPIDER-MAN (2002),The Avengers (2012) and Spider-Man (2002) are superhero movies from different franchises.
16,16,X-MEN: FIRST CLASS (2011),IRON MAN (2008),X-Men: First Class (2011) and Iron Man (2008) are superhero movies from different franchises.
17,17,IRON MAN (2008),X-MEN: THE LAST STAND (2006),X-Men: The Last Stand (2006) and Iron Man (2008) are superhero movies from different franchises.
18,18,QUENTIN TARANTINO,PULP FICTION (1994),"Quentin Tarantino directed Pulp Fiction, a groundbreaking film from 1994."
19,19,JOHN TRAVOLTA,PULP FICTION (1994),"John Travolta stars in Pulp Fiction, showcasing his versatility as an actor."
20,20,SAMUEL L. JACKSON,PULP FICTION (1994),"Samuel L. Jackson stars in Pulp Fiction, delivering a memorable performance."
21,21,UMA THURMAN,PULP FICTION (1994),"Uma Thurman stars in Pulp Fiction, known for her iconic role."
22,22,MEN: THE LAST STAND (2006),X-MEN,X-Men: The Last Stand (2006) is part of the X-Men franchise
23,23,AVENGERS: INFINITY WAR (2018),SUPERHERO,Avengers: Infinity War (2018) is a superhero film featuring a massive ensemble of Marvel superheroes battling against the threat of Thanos.\nAvengers: Infinity War (2018) is a superhero film
24,24,IT (2017),HORROR,"It (2017) is a horror film based on Stephen King's novel, featuring the terrifying entity Pennywise.\nIt (2017) is a horror film"
25,25,IT (1990),HORROR,"It (1990) is a horror miniseries\nIt (1990) is a horror miniseries based on Stephen King's novel, depicting a group of kids confronting the malevolent entity Pennywise."
26,26,THE EXORCIST (1973),HORROR,"The Exorcist (1973) is a horror film renowned for its chilling portrayal of demonic possession and exorcism, directed by William Friedkin.\nThe Exorcist (1973) is a horror film"
27,27,THE LAST EXORCISM (2010),HORROR,The Last Exorcism (2010) is a horror film\nThe Last Exorcism (2010) is a horror film following a fraudulent exorcist encountering genuine evil during his final exorcism.
28,28,CLICK (2006),COMEDY-DRAMA,"Click (2006) is a comedy-drama film starring Adam Sandler\nClick (2006) is a comedy-drama film starring Adam Sandler, where a man's life changes with a magical remote control."
29,29,THE MASK (1988),COMEDY,"The Mask (1988) is a comedy film\nThe Mask (1988) is a comedy film starring Jim Carrey, where a magical mask transforms a timid man into a mischievous character."
30,30,SON OF THE MASK (2005),COMEDY,Son of the Mask (2005) is a comedy film\nSon of the Mask (2005) is a comedy film continuing the adventures of a baby with extraordinary powers from the magical mask.
31,31,YOU DON'T MESS WITH THE ZOHAN (2008),COMEDY,You Don't Mess with the Zohan (2008) is a comedy film\nYou Don't Mess with the Zohan (2008) is a comedy film starring Adam Sandler as an ex-Israeli soldier pursuing a career in hairstyling.
32,32,IRON MAN (2008),SUPERHERO,"Iron Man (2008) is a superhero film directed by Jon Favreau, introducing the character Tony Stark/Iron Man portrayed by Robert Downey Jr.\nIron Man (2008) is a superhero film"
33,33,SPIDER-MAN 3 (2007),SUPERHERO,"Spider-Man 3 (2007) is a superhero film\nSpider-Man 3 (2007) is a superhero film directed by Sam Raimi, featuring Peter Parker/Spider-Man facing internal struggles and new adversaries."
34,34,SPIDER-MAN: HOMECOMING (2017),SUPERHERO,"Spider-Man: Homecoming (2017) is a superhero film\nSpider-Man: Homecoming (2017) is a superhero film directed by Jon Watts, focusing on a young Peter Parker balancing high school life and superhero duties."

In [22]:
!pip install dataframe_image

Collecting dataframe_image
  Downloading dataframe_image-0.2.7-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pandas>=0.24 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from dataframe_image) (2.2.3)
Collecting nbconvert>=5 (from dataframe_image)
  Downloading nbconvert-7.16.6-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: aiohttp>=3.10.2 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from dataframe_image) (3.11.12)
Requirement already satisfied: requests in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from dataframe_image) (2.32.3)
Requirement already satisfied: pillow in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from dataframe_image) (11.1.0)
Requirement already satisfied: packaging in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from dataframe_image) (24.2)
Collecting mistune (from dataframe_image)
  Downloading mistune-3.1.2-py3-none-any.whl.metadata (1.7 kB)
Collecting lxml (from dataframe_image)
  Downloading lxml-5.3.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting beautifulsoup4 (from dataframe_image)
  Downloading beautifulsoup4-4.13.3-py3-none-any.whl.metadata (3.8 kB)
Collecting cssutils (from dataframe_image)
  Downloading cssutils-2.11.1-py3-none-any.whl.metadata (8.7 kB)
Collecting playwright (from dataframe_image)
  Downloading playwright-1.51.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Collecting cssselect (from dataframe_image)
  Downloading cssselect-1.3.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from aiohttp>=3.10.2->dataframe_image) (1.18.3)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert>=5->dataframe_image)
  Using cached bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Collecting defusedxml (from nbconvert>=5->dataframe_image)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: jinja2>=3.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from nbconvert>=5->dataframe_image) (3.1.5)
Requirement already satisfied: jupyter-core>=4.7 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from nbconvert>=5->dataframe_image) (5.7.2)
Collecting jupyterlab-pygments (from nbconvert>=5->dataframe_image)
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: markupsafe>=2.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from nbconvert>=5->dataframe_image) (3.0.2)
Collecting nbclient>=0.5.0 (from nbconvert>=5->dataframe_image)
  Downloading nbclient-0.10.2-py3-none-any.whl.metadata (8.3 kB)
Collecting nbformat>=5.7 (from nbconvert>=5->dataframe_image)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert>=5->dataframe_image)
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: pygments>=2.4.1 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from nbconvert>=5->dataframe_image) (2.19.1)
Requirement already satisfied: traitlets>=5.1 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from nbconvert>=5->dataframe_image) (5.14.3)
Requirement already satisfied: typing-extensions in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from mistune->dataframe_image) (4.12.2)
Requirement already satisfied: numpy>=1.22.4 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from pandas>=0.24->dataframe_image) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from pandas>=0.24->dataframe_image) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from pandas>=0.24->dataframe_image) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from pandas>=0.24->dataframe_image) (2024.2)
Collecting soupsieve>1.2 (from beautifulsoup4->dataframe_image)
  Using cached soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Collecting more-itertools (from cssutils->dataframe_image)
  Downloading more_itertools-10.6.0-py3-none-any.whl.metadata (37 kB)
Collecting pyee<13,>=12 (from playwright->dataframe_image)
  Downloading pyee-12.1.1-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright->dataframe_image)
  Downloading greenlet-3.1.1-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from requests->dataframe_image) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from requests->dataframe_image) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from requests->dataframe_image) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from requests->dataframe_image) (2024.12.14)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->dataframe_image)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert>=5->dataframe_image)
  Using cached tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: platformdirs>=2.5 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe_image) (4.3.6)
Requirement already satisfied: jupyter-client>=6.1.12 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from nbclient>=0.5.0->nbconvert>=5->dataframe_image) (8.6.3)
Collecting fastjsonschema>=2.15 (from nbformat>=5.7->nbconvert>=5->dataframe_image)
  Using cached fastjsonschema-2.21.1-py3-none-any.whl.metadata (2.2 kB)
Collecting jsonschema>=2.6 (from nbformat>=5.7->nbconvert>=5->dataframe_image)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: six>=1.5 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=0.24->dataframe_image) (1.17.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5->dataframe_image)
  Using cached jsonschema_specifications-2024.10.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5->dataframe_image)
  Downloading referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5->dataframe_image)
  Downloading rpds_py-0.23.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: pyzmq>=23.0 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (26.2.0)
Requirement already satisfied: tornado>=6.2 in /home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (6.4.2)
Downloading dataframe_image-0.2.7-py3-none-any.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 9.6 MB/s eta 0:00:00a 0:00:01m
Downloading nbconvert-7.16.6-py3-none-any.whl (258 kB)
Downloading mistune-3.1.2-py3-none-any.whl (53 kB)
Downloading beautifulsoup4-4.13.3-py3-none-any.whl (186 kB)
Downloading cssselect-1.3.0-py3-none-any.whl (18 kB)
Downloading cssutils-2.11.1-py3-none-any.whl (385 kB)
Downloading lxml-5.3.1-cp310-cp310-manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 9.5 MB/s eta 0:00:00ta 0:00:01
Downloading playwright-1.51.0-py3-none-manylinux1_x86_64.whl (45.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 MB 9.3 MB/s eta 0:00:0000:0100:01
Using cached bleach-6.2.0-py3-none-any.whl (163 kB)
Downloading greenlet-3.1.1-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (599 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 599.5/599.5 kB 10.3 MB/s eta 0:00:00
Downloading nbclient-0.10.2-py3-none-any.whl (25 kB)
Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Using cached pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Downloading pyee-12.1.1-py3-none-any.whl (15 kB)
Using cached soupsieve-2.6-py3-none-any.whl (36 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Downloading more_itertools-10.6.0-py3-none-any.whl (63 kB)
Using cached fastjsonschema-2.21.1-py3-none-any.whl (23 kB)
Using cached jsonschema-4.23.0-py3-none-any.whl (88 kB)
Using cached tinycss2-1.4.0-py3-none-any.whl (26 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Using cached jsonschema_specifications-2024.10.1-py3-none-any.whl (18 kB)
Downloading referencing-0.36.2-py3-none-any.whl (26 kB)
Downloading rpds_py-0.23.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (386 kB)
Installing collected packages: webencodings, fastjsonschema, tinycss2, soupsieve, rpds-py, pyee, pandocfilters, more-itertools, mistune, lxml, jupyterlab-pygments, greenlet, defusedxml, cssselect, bleach, referencing, playwright, cssutils, beautifulsoup4, jsonschema-specifications, jsonschema, nbformat, nbclient, nbconvert, dataframe_image
Successfully installed beautifulsoup4-4.13.3 bleach-6.2.0 cssselect-1.3.0 cssutils-2.11.1 dataframe_image-0.2.7 defusedxml-0.7.1 fastjsonschema-2.21.1 greenlet-3.1.1 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 jupyterlab-pygments-0.3.0 lxml-5.3.1 mistune-3.1.2 more-itertools-10.6.0 nbclient-0.10.2 nbconvert-7.16.6 nbformat-5.10.4 pandocfilters-1.5.1 playwright-1.51.0 pyee-12.1.1 referencing-0.36.2 rpds-py-0.23.1 soupsieve-2.6 tinycss2-1.4.0 webencodings-0.5.1

In [31]:
community_df = pd.read_parquet(r"/home/Nema/UniCRS_GraphRAG/Recommendation_GraphRAG/output/test_dialogue/artifacts/create_final_community_reports.parquet")
community_df[['human_readable_id', 'title', 'summary', 'full_content', 'rank_explanation', 'findings', 'full_content_json']]

,human_readable_id,title,summary,full_content,rank_explanation,findings,full_content_json
0,0,Avengers: Infinity War (2018) and Emma Stone's Impact,"This community centers around the movie Avengers: Infinity War (2018), a superhero film featuring the Avengers battling against Thanos. It also highlights Emma Stone's role in Easy A (2010) and her broader impact as an actress.","# Avengers: Infinity War (2018) and Emma Stone's Impact\n\nThis community centers around the movie Avengers: Infinity War (2018), a superhero film featuring the Avengers battling against Thanos. It also highlights Emma Stone's role in Easy A (2010) and her broader impact as an actress.\n\n## Avengers: Infinity War (2018) as a superhero ensemble film\n\nAvengers: Infinity War (2018) stands out as a superhero ensemble film featuring a massive cast of Marvel superheroes, including the Avengers, in a battle against the formidable threat of Thanos. The movie's narrative complexity and visual spectacle have contributed to its cultural significance. [Data: Entities (16); Relationships (23)]\n\n## Emma Stone's performance in Easy A (2010)\n\nEmma Stone's portrayal in Easy A (2010) showcases her talent as an actress. Her role in the comedy film has been pivotal in establishing her as a versatile performer with a knack for comedic timing and emotional depth. [Data: Entities (15, 31); Relationships (11)]\n\n## Cross-genre appeal of Easy A (2010)\n\nEasy A (2010) and Avengers: Infinity War (2018) represent movies from different genres, highlighting the diverse range of films within this community. The cross-genre appeal of Easy A further demonstrates the versatility of the community's key entities. [Data: Relationships (10)]",The impact severity rating reflects the significant cultural influence of Avengers: Infinity War (2018) and Emma Stone's contributions to the film industry.,"[{'explanation': 'Avengers: Infinity War (2018) stands out as a superhero ensemble film featuring a massive cast of Marvel superheroes, including the Avengers, in a battle against the formidable threat of Thanos. The movie's narrative complexity and visual spectacle have contributed to its cultural significance. [Data: Entities (16); Relationships (23)]', 'summary': 'Avengers: Infinity War (2018) as a superhero ensemble film'}, {'explanation': 'Emma Stone's portrayal in Easy A (2010) showcases her talent as an actress. Her role in the comedy film has been pivotal in establishing her as a versatile performer with a knack for comedic timing and emotional depth. [Data: Entities (15, 31); Relationships (11)]', 'summary': 'Emma Stone's performance in Easy A (2010)'}, {'explanation': 'Easy A (2010) and Avengers: Infinity War (2018) represent movies from different genres, highlighting the diverse range of films within this community. The cross-genre appeal of Easy A further demonstrates the versatility of the community's key entities. [Data: Relationships (10)]', 'summary': 'Cross-genre appeal of Easy A (2010)'}]","{\n ""title"": ""Avengers: Infinity War (2018) and Emma Stone's Impact"",\n ""summary"": ""This community centers around the movie Avengers: Infinity War (2018), a superhero film featuring the Avengers battling against Thanos. It also highlights Emma Stone's role in Easy A (2010) and her broader impact as an actress."",\n ""findings"": [\n {\n ""summary"": ""Avengers: Infinity War (2018) as a superhero ensemble film"",\n ""explanation"": ""Avengers: Infinity War (2018) stands out as a superhero ensemble film featuring a massive cast of Marvel superheroes, including the Avengers, in a battle against the formidable threat of Thanos. The movie's narrative complexity and visual spectacle have contributed to its cultural significance. [Data: Entities (16); Relationships (23)]""\n },\n {\n ""summary"": ""Emma Stone's performance in Easy A (2010)"",\n ""explanation"": ""Emma Stone's portrayal in Easy A (2010) showcases her talent as an actress. Her role in the comedy film has been pivotal in establishing her as a versatile performer with a knack for comedic timing and emotional depth. [Data: Entities (15, 31); Relationships (11)]""\n },\n {\n ""summary"": ""Cross-genre appeal of Easy A (2010)"",\n ""explanation"": ""Easy A (2010) and Avengers: Infinity War (2018) represent movies from different genres, highlighting the diverse range of films within this community. The cross-genre appeal of Easy A further demonstrates the versatility of the community's key entities. [Data: Relationships (10)]""\n }\n ],\n ""rating"": 7.5,\n ""rating_explanation"": ""The impact severity rating reflects the significant cultural influence of Avengers: Infinity War (2018) and Emma Stone's contributions to the film industry.""\n}"
1,1,Spider-Man Movie Community,"This community revolves around the Spider-Man movie franchise, including Spider-Man 3 (2007) directed by Sam Raimi and Spider-Man: Homecoming (2017) directed by Jon Watts. These films feature the iconic character Peter Parker/Spider-Man facing internal conflicts and battling against various adversaries, embodying the superhero genre's essence.","# Spider-Man Movie Community\n\nThis community revolves around the Spider-Man movie franchise, including Spider-Man 3 (2007) directed by Sam Raimi and Spider-Man: Homecoming (2017) directed by Jon Watts. These films feature the iconic character Peter Parker/Spider-Man facing internal conflicts and battling against various adversaries, embodying the superhero genre's essence.\n\n## Spider-Man 3 (2007) as a pivotal movie\n\nSpider-Man 3 (2007) directed by Sam Raimi is a pivotal movie in this community, showcasing Peter Parker/Spider-Man's internal struggles and battles against new foes. The film's narrative complexity and character development have contributed to its enduring legacy in the superhero genre. [Data: Entities (45); Relationships (33)]\n\n## Spider-Man: Homecoming (2017) and the franchise's evolution\n\nSpider-Man: Homecoming (2017) directed by Jon Watts represents the franchise's evolution, focusing on a young Peter Parker balancing high school life with superhero responsibilities. The film's fresh take on the character and engaging storytelling have resonated with audiences, solidifying Spider-Man's cultural relevance. [Data: Entities (46); Relationships (34)]\n\n## Avengers: Infinity War (2018) and the interconnected universe\n\nAvengers: Infinity War (2018) features Spider-Man alongside a massive ensemble of Marvel superheroes, highlighting the interconnected nature of the Marvel Cinematic Universe. The film's success and critical acclaim underscore the collaborative efforts within the superhero genre, showcasing Spider-Man's integration into a larger cinematic universe. [Data: Relationships (23)]\n\n## Cultural impact of Spider-Man\n\nThe Spider-Man movie community has had a significant cultural impact, with the character of Peter Parker/Spider-Man becoming an iconic figure in popular culture. The themes of heroism, responsibility, and identity explored in the films resonate with audiences of all ages, contributing to the enduring appeal of the superhero genre. [Inferred Insight]\n\n## Genre dominance in superhero storytelling\n\nThe Spider-Man movie community exemplifies the dominance of the superhero genre in modern storytelling, with its blend of action, drama, and character-driven narratives captivating global audiences. The franchise's ability to balance spectacle with emotional depth has set a benchmark for superhero films, influencing the genre's evolution over the years. [Inferred Insight]","The impact severity rating is high due to the enduring popularity and cultural significance of the Spider-Man movie franchise, showcasing the evolution of the superhero genre in cinema.","[{'explanation': 'Spider-Man 3 (2007) directed by Sam Raimi is a pivotal movie in this community, showcasing Peter Parker/Spider-Man's internal struggles and battles against new foes. The film's narrative complexity and character development have contributed to its enduring legacy in the superhero genre. [Data: Entities (45); Relationships (33)]', 'summary': 'Spider-Man 3 (2007) as a pivotal movie'}, {'explanation': 'Spider-Man: Homecoming (2017) directed by Jon Watts represents the franchise's evolution, focusing on a young Peter Parker balancing high school life with superhero responsibilities. The film's fresh take on the character and engaging storytelling have resonated with audiences, solidifying Spider-Man's cultural relevance. [Data: Entities (46); Relationships (34)]', 'summary': 'Spider-Man: Homecoming (2017) and the franchise's evolution'}, {'explanation': 'Avengers: Infinity War (2018) features Spider-Man alongside a massive ensemble of Marvel superheroes, highlighting the interconnected nature of the Marvel Cinematic Universe. The film's success and critical acclaim underscore the collaborative efforts within the superhero genre, showcasing Spider-Man's integration into a larger cinematic universe. [Data: Relationships (23)]', 'summary': 'Avengers: Infinity War (2018) and the interconnected universe'}, {'explanation': 'The Spider-Man movie community has had a significant cultural impact, with the character of Peter Parker/Spider-Man becoming an iconic figure in popular culture. The themes of heroism, responsibility, and identity explored in the films resonate with audiences of all ages, contributing to the enduring appeal of the superhero genre. [Inferred Insight]', 'summary': 'Cultural impact of Spider-Man'}, {'explanation': 'The Spider-Man movie community exemplifies the dominance of the superhero genre in modern storytelling, with its blend of action, drama, and character-driven narratives captivating global audiences. The franchise's ability to balance spectacle with emotional depth has set a benchmark for superhero films, influencing the genre's evolution over the years. [Inferred Insight]', 'summary': 'Genre dominance in superhero storytelling'}]","{\n ""title"": ""Spider-Man Movie Community"",\n ""summary"": ""This community revolves around the Spider-Man movie franchise, including Spider-Man 3 (2007) directed by Sam Raimi and Spider-Man: Homecoming (2017) directed by Jon Watts. These films feature the iconic character Peter Parker/Spider-Man facing internal conflicts and battling against various adversaries, embodying the superhero genre's essence."",\n ""findings"": [\n {\n ""summary"": ""Spider-Man 3 (2007) as a pivotal movie"",\n ""explanation"": ""Spider-Man 3 (2007) directed by Sam Raimi is a pivotal movie in this community, showcasing Peter Parker/Spider-Man's internal struggles and battles against new foes. The film's narrative complexity and character development have contributed to its enduring legacy in the superhero genre. [Data: Entities (45); Relationships (33)]""\n },\n {\n ""summary"": ""Spider-Man: Homecoming (2017) and the franchise's evolution"",\n ""explanation"": ""Spider-Man: Homecoming (2017) directed by Jon Watts represents the franchise's evolution, focusing on a young Peter Parker balancing high school life with superhero responsibilities. The film's fresh take on the character and engaging storytelling have resonated with audiences, solidifying Spider-Man's cultural relevance. [Data: Entities (46); Relationships (34)]""\n },\n {\n ""summary"": ""Avengers: Infinity War (2018) and the interconnected universe"",\n ""explanation"": ""Avengers: Infinity War (2018) features Spider-Man alongside a massive ensemble of Marvel superheroes, highlighting the interconnected nature of the Marvel Cinematic Universe. The film's success and critical acclaim underscore the collaborative efforts within the superhero genre, showcasing Spider-Man's integration into a larger cinematic universe. [Data: Relationships (23)]""\n },\n {\n ""summary"": ""Cultural impact of Spider-Man"",\n ""explanation"": ""The Spider-Man movie community has had a significant cultural impact, with the character of Peter Parker/Spider-Man becoming an iconic figure in popular culture. The themes of heroism, responsibility, and identity explored in the films resonate with audiences of all ages, contributing to the enduring appeal of the superhero genre. [Inferred Insight]""\n },\n {\n ""summary"": ""Genre dominance in superhero storytelling"",\n ""explanation"": ""The Spider-Man movie community exemplifies the dominance of the superhero genre in modern storytelling, with its blend of action, drama, and character-driven narratives captivating global audiences. The franchise's ability to balance spectacle with emotional depth has set a benchmark for superhero films, influencing the genre's evolution over the years. [Inferred Insight]""\n }\n ],\n ""rating"": 8.0,\n ""rating_explanation"": ""The impact severity rating is high due to the enduring popularity and cultural significance of the Spider-Man movie franchise, showcasing the evolution of the superhero genre in cinema.""\n}"
2,2,Marvel vs. X-Men: Clash of Superheroes,"This community showcases the clash between two iconic superhero franchises, Marvel and X-Men, through movies like Iron Man (2008) and X-Men: First Class (2011). It highlights the introduction of key characters like Tony Stark/Iron Man and the cultural significance of these superhero films.","# Marvel vs. X-Men: Clash of Superheroes\n\nThis community showcases the clash between two iconic superhero franchises, Marvel and X-Men, through movies like Iron Man (2008) and X-Men: First Class (2011). It highlights the introduction of key characters like Tony Stark/Iron Man and the cultural significance of these superhero films.\n\n## Iron Man's introduction to the Marvel Cinematic Universe\n\nIron Man (2008) marks the introduction of Tony Stark/Iron Man, portrayed by Robert Downey Jr., to the Marvel Cinematic Universe. The film's success laid the foundation for the interconnected superhero universe that followed, establishing Iron Man as a central figure in the franchise. [Data: Entities (26); Relationships (17)]\n\n## X-Men: First Class as a pivotal entry in the X-Men franchise\n\nX-Men: First Class (2011) is a significant installment in the X-Men franchise, exploring the origins of the mutant team. The film's focus on character development and historical context sets it apart within the superhero genre, contributing to the rich narrative of the X-Men universe. [Data: Entities (25); Relationships (16)]\n\n## Cross-franchise collaboration between Marvel and X-Men\n\nThe relationship between Iron Man (2008) and X-Men: First Class (2011) represents a unique cross-franchise collaboration between Marvel and X-Men properties. This collaboration showcases the diversity and depth of superhero storytelling, bringing together iconic characters from different universes. [Data: Relationships (16, 17)]","The impact severity rating reflects the cultural significance of the clash between Marvel and X-Men franchises, as portrayed in Iron Man (2008) and X-Men: First Class (2011), and their influence on the superhero genre.","[{'explanation': 'Iron Man (2008) marks the introduction of Tony Stark/Iron Man, portrayed by Robert Downey Jr., to the Marvel Cinematic Universe. The film's success laid the foundation for the interconnected superhero universe that followed, establishing Iron Man as a central figure in the franchise. [Data: Entities (26); Relationships (17)]', 'summary': 'Iron Man's introduction to the Marvel Cinematic Universe'}, {'explanation': 'X-Men: First Class (2011) is a significant installment in the X-Men franchise, exploring the origins of the mutant team. The film's focus on character development and historical context sets it apart within the superhero genre, contributing to the rich narrative of the X-Men universe. [Data: Entities (25); Relationships (16)]', 'summary': 'X-Men: First Class as a pivotal entry in the X-Men franchise'}, {'explanation': 'The relationship between Iron Man (2008) and X-Men: First Class (2011) represents a unique cross-franchise collaboration between Marvel and X-Men properties. This collaboration showcases the diversity and depth of superhero storytelling, bringing together iconic characters from different universes. [Data: Relationships (16, 17)]', 'summary': 'Cross-franchise collaboration between Marvel and X-Men'}]","{\n ""title"": ""Marvel vs. X-Men: Clash of Superheroes"",\n ""summary"": ""This community showcases the clash between two iconic superhero franchises, Marvel and X-Men, through movies like Iron Man (2008) and X-Men: First Class (2011). It highlights the introduction of key characters like Tony Stark/Iron Man and the cultural significance of these superhero films."",\n ""findings"": [\n {\n ""summary"": ""Iron Man's introduction to the Marvel Cinematic Universe"",\n ""explanation"": ""Iron Man (2008) marks the introduction of Tony Stark/Iron Man, portrayed by Robert Downey Jr., to the Marvel Cinematic Universe. The film's success laid the foundation for the interconnected superhero universe that followed, establishing Iron Man as a central figure in the franchise. [Data: Entities (26); Relationships (17)]""\n },\n {\n ""summary"": ""X-Men: First Class as a pivotal entry in the X-Men franchise"",\n ""explanation"": ""X-Men: First Class (2011) is a significant installment in the X-Men franchise, exploring the origins of the mutant team. The film's focus on character development and historical context sets it apart within the superhero genre, contributing to the rich narrative of the X-Men universe. [Data: Entities (25); Relationships (16)]""\n },\n {\n ""summary"": ""Cross-franchise collaboration between Marvel and X-Men"",\n ""explanation"": ""The relationship between Iron Man (2008) and X-Men: First Class (2011) represents a unique cross-franchise collaboration between Marvel and X-Men properties. This collaboration showcases the diversity and depth of superhero storytelling, bringing together iconic characters from different universes. [Data: Relationships (16, 17)]""\n }\n ],\n ""rating"": 7.5,\n ""rating_explanation"": ""The impact severity rating reflects the cultural significance of the clash between Marvel and X-Men franchises, as portrayed in Iron Man (2008) and X-Men: First Class (2011), and their influence on the superhero genre.""\n}"

In [32]:
import matplotlib.pyplot as plt
import dataframe_image as dfi

# Load your dataframe (assuming it's already loaded)
row_index = 0  # Change this to the index of the record you want

# Extract a single row and format it
record = community_df.loc[row_index][['human_readable_id', 'title', 'summary', 'full_content', 
                         'rank_explanation', 'findings', 'full_content_json']].to_frame().T 

# Select columns and convert single row to a DataFrame
dfi.export(record, 'record.png')

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

In [4]:
df = pd.read_parquet("/home/Nema/UniCRS_GraphRAG/Recommendation_GraphRAG/output/train_step504/artifacts/create_final_entities.parquet")
df

,id,human_readable_id,title,type,description,text_unit_ids
0,7815e8e2-8cf5-4df4-920b-67d681385030,0,JUST GO WITH IT (2011),MOVIE,A comedy movie released in 2011,[877ade0ee628073ae354d15d0a76db613faaaab42470c...
1,b8d7f7d2-52f4-4766-a9e9-48dceca621b3,1,LOVE DON'T COST A THING (2003),MOVIE,A romantic comedy movie released in 2003,[877ade0ee628073ae354d15d0a76db613faaaab42470c...
2,5ae5af5a-5eed-4225-8030-d17b4f14ae41,2,MEAN GIRLS 2,MOVIE,A comedy movie released as a sequel to Mean Girls,[877ade0ee628073ae354d15d0a76db613faaaab42470c...
3,c718be12-2cd9-4259-b2cc-9fb0ca718967,3,MOMS' NIGHT OUT (2014),MOVIE,A family comedy movie released in 2014,[877ade0ee628073ae354d15d0a76db613faaaab42470c...
4,18d88d78-643a-49a1-aad8-435bf42d942e,4,WONDER (2017),MOVIE,A family drama movie released in 2017,[877ade0ee628073ae354d15d0a76db613faaaab42470c...
...,...,...,...,...,...,...
256,3f761b81-aca3-484a-84ba-0ef513df92e7,256,THE CONJURING 2 (2016),MOVIE,A 2016 horror movie titled The Conjuring 2,[ff907daf7a9914c289edffd3197be57d126657332fee4...
257,6203b744-9e3e-46f6-a9c9-70388e3f5b82,257,ANNABELLE,ACTOR,Character in the movie Annabelle: Creation (2017),[ff907daf7a9914c289edffd3197be57d126657332fee4...
258,a22adc89-11f8-446f-a14e-d9f2bdfa92f2,258,JOHN GOODMAN,ACTOR,Actor in 10 Cloverfield Lane (2016),[ff907daf7a9914c289edffd3197be57d126657332fee4...
259,f72b8425-1a8b-45a8-8fd8-c0180d15c47b,259,VERA FARMIGA,ACTOR,Actress in The Conjuring 2 (2016),[ff907daf7a9914c289edffd3197be57d126657332fee4...
260,1bda422b-7d39-4f27-be82-a861def8844f,260,CHUCKY,,,[ff907daf7a9914c289edffd3197be57d126657332fee4...

In [15]:
df2 = pd.read_parquet("/home/Nema/UniCRS_GraphRAG/GraphRAG/output/successful_20250129-110435/artifacts/create_final_community_reports.parquet")
df2

,id,human_readable_id,community,parent,level,title,summary,full_content,rank,rank_explanation,findings,full_content_json,period,size
0,a6d11470f41f4ce0857ee2c9ec2f9a70,2200,2200,1618,4,Star Wars (1977) and George Lucas' Impact,This community revolves around the iconic movi...,# Star Wars (1977) and George Lucas' Impact\n\...,9.0,The impact severity rating is high due to the ...,[{'explanation': 'Star Wars (1977) stands out ...,"{\n ""title"": ""Star Wars (1977) and George L...",2025-01-29,4
1,aa3e76b5eb8a4cbaa7ed616a86ed9700,2201,2201,1618,4,Exploring Robots in Cinema: Bicentennial Man (...,This community delves into the portrayal of ro...,# Exploring Robots in Cinema: Bicentennial Man...,7.5,The impact severity rating reflects the cultur...,[{'explanation': 'Bicentennial Man (1999) stan...,"{\n ""title"": ""Exploring Robots in Cinema: B...",2025-01-29,3
2,bbdd83641cd24effa306de3ca7bf2c87,2202,2202,1618,4,Star Wars Saga and George Lucas' Impact,This community revolves around the iconic Star...,# Star Wars Saga and George Lucas' Impact\n\nT...,9.0,The impact severity rating is high due to the ...,[{'explanation': 'The Empire Strikes Back (198...,"{\n ""title"": ""Star Wars Saga and George Luc...",2025-01-29,4
3,deb2fc15b3134a3b81994c8b7034a630,2203,2203,1622,4,Star Wars Franchise and Its Impact on Sci-Fi C...,This community revolves around the iconic Star...,# Star Wars Franchise and Its Impact on Sci-Fi...,9.2,The impact severity rating is high due to the ...,[{'explanation': 'The Empire Strikes Back is a...,"{\n ""title"": ""Star Wars Franchise and Its I...",2025-01-29,8
4,e1ad5a88df374a7fb0d4b37cc717189b,2204,2204,1622,4,Let It Go and Its Movie Community Connections,This community revolves around the song Let It...,# Let It Go and Its Movie Community Connection...,7.5,The impact severity rating reflects the signif...,[{'explanation': 'Let It Go serves as the foca...,"{\n ""title"": ""Let It Go and Its Movie Commu...",2025-01-29,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2223,976c20fa93d74066b5a57113979c26ea,32,32,-1,0,Steven Seagal's Action Movie Community,"This community revolves around Steven Seagal, ...",# Steven Seagal's Action Movie Community\n\nTh...,8.2,The impact severity rating reflects the enduri...,[{'explanation': 'Steven Seagal serves as the ...,"{\n ""title"": ""Steven Seagal's Action Movie ...",2025-01-29,10
2224,12db44a1af78422b9e80138c361e0508,33,33,-1,0,Weird and Wonderful: A Look into Quirky Movies,This community showcases a collection of quirk...,# Weird and Wonderful: A Look into Quirky Movi...,7.2,The impact severity rating reflects the cultur...,[{'explanation': 'The SpongeBob SquarePants Mo...,"{\n ""title"": ""Weird and Wonderful: A Look i...",2025-01-29,8
2225,eaafd1da79f54374b0b1bc3a4aa40cd4,34,34,-1,0,Spanish Cinema Community: Pedro Almodovar's Im...,This community revolves around key Spanish mov...,# Spanish Cinema Community: Pedro Almodovar's ...,9.0,The impact severity rating is high due to the ...,[{'explanation': 'Pedro Almodovar stands out a...,"{\n ""title"": ""Spanish Cinema Community: Ped...",2025-01-29,12
2226,f20aa1d5956648eea88399bd181d2b97,35,35,-1,0,Vampire and Werewolf Movie Community,This community revolves around movies that fea...,# Vampire and Werewolf Movie Community\n\nThis...,9.2,The impact severity rating is high due to the ...,[{'explanation': 'The community is characteriz...,"{\n ""title"": ""Vampire and Werewolf Movie Co...",2025-01-29,93
2227,f1fea4dc7c1641b5bc476f7283478056,36,36,-1,0,Nerve (2016) and Emma Roberts' Impact,This community revolves around the movie Nerve...,# Nerve (2016) and Emma Roberts' Impact\n\nThi...,8.2,The impact severity rating is high due to the ...,[{'explanation': 'Nerve (2016) is the focal po...,"{\n ""title"": ""Nerve (2016) and Emma Roberts...",2025-01-29,12

In [16]:
df2.iloc[0]['findings']

array([{'explanation': 'Star Wars (1977) stands out as a cultural phenomenon that has captivated audiences worldwide. Its innovative storytelling, memorable characters, and groundbreaking visual effects have solidified its status as a timeless classic. [Data: Entities (627); Relationships (1697, 741, 27198, 29274)]', 'summary': 'Star Wars (1977) as a cultural phenomenon'},
       {'explanation': "The Empire Strikes Back (1980) is a pivotal sequel in the Star Wars series, often regarded as superior to the original film. Its narrative depth, character development, and iconic moments have contributed significantly to the franchise's enduring legacy. [Data: Relationships (1697)]", 'summary': 'The impact of The Empire Strikes Back (1980)'},
       {'explanation': 'The Machete Order offers a unique perspective on the Star Wars saga by rearranging the viewing sequence of the movies. This alternative order enhances the storytelling and character arcs, providing fans with a fresh and engaging way to experience the franchise. [Data: Relationships (27198)]', 'summary': "Machete Order's unique viewing experience"},
       {'explanation': "George Lucas' visionary creation of Star Wars has reshaped the landscape of filmmaking. His innovative approach to storytelling, world-building, and visual effects has set new standards in the industry and inspired generations of filmmakers. [Data: Entities (11010); Relationships (29274)]", 'summary': "George Lucas' visionary creation"}],
      dtype=object)

In [12]:
df2.to_csv("/home/Nema/UniCRS_GraphRAG/Recommendation_GraphRAG/output/create_final_community_reports.csv")